# Generated by Django 5.1 on 2025-01-16 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
