# Generated by Django 5.1.3 on 2024-11-26 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options_branch_created_at_and_more'),
        ('rooms', '0002_room_branch_room_created_at_room_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
    ]
