# Generated by Django 5.1.3 on 2024-12-12 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFunnelStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название этапа')),
                ('order', models.PositiveIntegerField(verbose_name='Порядок этапа')),
            ],
            options={
                'verbose_name': 'Этап воронки',
                'verbose_name_plural': 'Этапы воронки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesFunnel.salesfunnelstage', verbose_name='Текущий этап')),
            ],
            options={
                'verbose_name': 'Лид',
                'verbose_name_plural': 'Лиды',
            },
        ),
        migrations.CreateModel(
            name='FunnelAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата действия')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesFunnel.lead', verbose_name='Лид')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesFunnel.salesfunnelstage', verbose_name='Этап')),
            ],
            options={
                'verbose_name': 'Действие воронки',
                'verbose_name_plural': 'Действия воронки',
            },
        ),
    ]
