# Generated by Django 5.1.3 on 2024-12-12 18:51

import sortedm2m.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesFunnel', '0003_alter_lead_email_alter_lead_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='current_stage',
        ),
        migrations.AddField(
            model_name='lead',
            name='stages',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='salesFunnel.salesfunnelstage', verbose_name='Этапы воронки'),
        ),
    ]
