# Generated by Django 5.1.3 on 2024-12-12 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesFunnel', '0004_remove_lead_current_stage_lead_stages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='stages',
        ),
        migrations.AddField(
            model_name='lead',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesFunnel.salesfunnelstage', verbose_name='Текущий этап'),
        ),
    ]
