# Generated by Django 5.1.3 on 2024-11-24 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branch_options_branch_created_at_and_more'),
        ('groups', '0001_initial'),
        ('teachers', '0002_remove_teacher_name_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_teachers', to='groups.group')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_conductings', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'group')},
            },
        ),
    ]
