# Generated by Django 5.1.3 on 2024-11-24 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupMemberships', '0001_initial'),
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_members', to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('student', 'group')},
        ),
    ]
