# Generated by Django 5.1.3 on 2024-11-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupMemberships', '0004_alter_groupmembership_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='enrolled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата записи'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Ожидает подтверждения'), ('enrolled', 'Записан'), ('studying', 'Обучается'), ('paused', 'На паузе'), ('completed', 'Завершил курс'), ('not_completed', 'Не завершил'), ('withdrawn', 'Отказался'), ('expelled', 'Исключён')], default='pending_approval', max_length=20, verbose_name='Статус'),
        ),
    ]
