# Generated by Django 5.1.3 on 2024-12-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupMemberships', '0005_groupmembership_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='first_month_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='last_month_payment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
