# Generated by Django 5.1.3 on 2024-12-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupMemberships', '0006_groupmembership_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembership',
            name='balance',
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='enrolled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата записи на курс'),
        ),
    ]
