# Generated by Django 5.1.3 on 2024-11-26 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0002_alter_branch_options_branch_created_at_and_more'),
        ('groups', '0005_alter_group_branch'),
        ('rooms', '0003_alter_room_branch'),
        ('teachers', '0004_alter_teacher_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('lesson_type', models.CharField(choices=[('regular', 'Regular'), ('trial', 'Trial'), ('rescheduled', 'Rescheduled'), ('one_time', 'One-Time'), ('other', 'Other')], default='regular', max_length=20, verbose_name='Lesson Type')),
                ('other_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Other Description')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='groups.group', verbose_name='Group')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='rooms.room', verbose_name='Room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='teachers.teacher', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('room', 'date', 'start_time'), name='unique_lesson')],
            },
        ),
    ]
