# Generated by Django 5.1.3 on 2024-11-26 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_branch_options_branch_created_at_and_more'),
        ('lessons', '0001_initial'),
        ('students', '0003_alter_student_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lessons.lesson', verbose_name='Lesson')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='students.student', verbose_name='Student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
