# Generated by Django 5.1.3 on 2024-12-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_previous_date_lesson_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lessonstudent',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина (если выбрано Другое)'),
        ),
    ]
